public enum ItemType
{
    TOMATO,LETTUCE,ONION,CHEESE,MEATBALL,BREAD,NONE,
    SLICEDTOM,SLICEDLET,SLICEDON,SLICEDCHE,COOKEDMEAT,SLICEDBREAD,PLATE,SlICEDBREADTOP,HAMBURGER,SYRUP,COFFEE1,COFFEE2,MILK,GROUNDCOFFEE,ESPRESSOMODEL,MILKCUP,LATTE
}
public interface IGetItem
{
    public ItemType GetItem();
} 
